import C3POCHEWBACCA from "./C3POCHEWBACCA";
import C3POLEGENDARY from "./C3POLEGENDARY";
import CHEWBACCALEGENDARY from "./CHEWBACCALEGENDARY";
import COMMANDERLUKESKYWALKER from "./COMMANDERLUKESKYWALKER";
import HANSOLO from "./HANSOLO";
import GRANDMASTERLUKE from "./GRANDMASTERLUKE/abilities";
import GENERALSKYWALKER from "./GENERALSKYWALKER/abilities";

export const abilitiesList = {
  C3POCHEWBACCA,
  C3POLEGENDARY,
  CHEWBACCALEGENDARY,
  COMMANDERLUKESKYWALKER,
  HANSOLO,
  GRANDMASTERLUKE,
  GENERALSKYWALKER,
};
