import GRANDMASTERLUKE from "./GRANDMASTERLUKE/character";
import GENERALSKYWALKER from "./GENERALSKYWALKER/character";

export default new Map([
  ["GRANDMASTERLUKE", GRANDMASTERLUKE],
  ["GENERALSKYWALKER", GENERALSKYWALKER],
]);
