import C3POCHEWBACCA from "./C3POCHEWBACCA";
import C3POLEGENDARY from "./C3POLEGENDARY";
// import AAYLASECURA from "./AAYLASECURA";
import CHEWBACCALEGENDARY from "./CHEWBACCALEGENDARY";
import COMMANDERLUKESKYWALKER from "./COMMANDERLUKESKYWALKER";
import HANSOLO from "./HANSOLO";
// import OLDBENKENOBI from "./OLDBENKENOBI";
// import ADMIRALACKBAR from "./ADMIRALACKBAR";

const characterMapping = {
  COMMANDERLUKESKYWALKER,
  // OLDBENKENOBI,
  // AAYLASECURA,
  HANSOLO,
  CHEWBACCALEGENDARY,
  C3POCHEWBACCA,
  C3POLEGENDARY,
};

export default characterMapping;
