import C3POCHEWBACCA from "./C3POCHEWBACCA";
import C3POLEGENDARY from "./C3POLEGENDARY";
import CHEWBACCALEGENDARY from "./CHEWBACCALEGENDARY";
import COMMANDERLUKESKYWALKER from "./COMMANDERLUKESKYWALKER";
import HANSOLO from "./HANSOLO";
import GRANDMASTERLUKE from "./GRANDMASTERLUKE";

const characterMapping = {
  C3POCHEWBACCA,
  C3POLEGENDARY,
  CHEWBACCALEGENDARY,
  COMMANDERLUKESKYWALKER,
  HANSOLO,
  GRANDMASTERLUKE,
};

export default characterMapping;
