stages:
  - build

build_project:
  image: node:18  # Use a Node.js version that matches your project
  stage: build
  script:
    - npm install
    - npm run build
    - git config --global user.email "ci-bot@example.com"
    - git config --global user.name "GitLab CI"
    - git add .
    - git commit -m "Automated build commit [skip ci]" || echo "No changes to commit"
    - git push
