import { iCharacter } from "./characters";

export const oldBen = {
  name: "Obi-Wan Kenobi (Old Ben)",
  id: "OLDBENKENOBI",
  activeAbilities: [
    "specialskill_OLDBENKENOBI02",
    "specialskill_OLDBENKENOBI01",
    "basicskill_OLDBENKENOBI",
  ],
  uniqueAbilities: ["uniqueskill_OLDBENKENOBI01"],
  stats: {
    maxHealth: 34584,
    health: 34584,
    protection: 43378,
    maxProtection: 43378,
    speed: 138,
    physical: {
      offense: 2518,
      critChance: 0.3017,
      armorPen: 20,
      accuracy: 0,
      armor: 740,
      dodge: 2,
      critAvoid: 0,
    },
    special: {
      offense: 2647,
      critChance: 0.125,
      armorPen: 5,
      accuracy: 0,
      armor: 583,
      dodge: 2,
      critAvoid: 0,
    },
    critDamage: 1.5,
    tenacity: 55,
    potency: 45,
    healthSteal: 0.2,
  },
  alignment: "Light Side" as iCharacter["alignment"],
  categories: ["Rebel", "Jedi", "Tank", "Leader"],
};

export const cls = {
  name: "Commander Luke Skywalker",
  id: "COMMANDERLUKESKYWALKER",
  activeAbilities: [
    "specialskill_COMMANDERLUKESKYWALKER02",
    "specialskill_COMMANDERLUKESKYWALKER01",
    "basicskill_COMMANDERLUKESKYWALKER",
  ],
  uniqueAbilities: [
    "uniqueskill_COMMANDERLUKESKYWALKER01",
    "uniqueskill_COMMANDERLUKESKYWALKER02",
  ],
  stats: {
    maxHealth: 30802,
    health: 30802,
    protection: 37634,
    maxProtection: 37634,
    speed: 172,
    physical: {
      offense: 3803,
      critChance: 0.5179,
      armorPen: 251,
      accuracy: 0,
      armor: 363,
      dodge: 2,
      critAvoid: 0,
    },
    special: {
      offense: 1877,
      critChance: 0.1083,
      armorPen: 0,
      accuracy: 0,
      armor: 227,
      dodge: 2,
      critAvoid: 0,
    },
    critDamage: 1.5,
    tenacity: 45,
    potency: 41,
    healthSteal: 10,
  },
  alignment: "Light Side" as iCharacter["alignment"],
  categories: ["Rebel", "Unaligned Force User", "Attacker", "Leader"],
};

export const aayla = {
  name: "Aayla Secura",
  id: "AAYLASECURA",
  activeAbilities: ["specialskill_AAYLASECURA01", "basicskill_AAYLASECURA"],
  uniqueAbilities: [],
  stats: {
    maxHealth: 32108,
    health: 32108,
    protection: 41388,
    maxProtection: 41388,
    speed: 145,
    physical: {
      offense: 3602,
      critChance: 0.5258,
      armorPen: 184,
      accuracy: 0,
      armor: 309,
      dodge: 2,
      critAvoid: 0,
    },
    special: {
      offense: 2356,
      critChance: 0.1,
      armorPen: 15,
      accuracy: 0,
      armor: 116,
      dodge: 2,
      critAvoid: 0,
    },
    critDamage: 1.5,
    tenacity: 50,
    potency: 41,
    healthSteal: 0.15,
  },
  alignment: "Light Side" as iCharacter["alignment"],
  categories: ["Rebel", "Unaligned Force User", "Attacker", "Leader"],
};
