import { Relic, RelicConfigType } from "./relic";

// export default {}

//https://docs.google.com/spreadsheets/d/10ReT0Q_4yYGd_fU45Clv7XYs23a96xpWgIxLVrg9Eqg/edit#gid=769217271
export default {
  fragmented_white: new Relic({
    id: "fragmented_white",
    location: {
      node: "Cantina 8-C",
      energy: 16,
    },
    dropRate: 1.37,
    amount: {
      1: 0,
      2: 15,
      3: 20,
      4: 20,
      5: 20,
      6: 20,
      7: 20,
      8: 20,
      9: 30,
    },
    image:
      "https://wiki.swgoh.help/images/0/08/Gear-Fragmented_Signal_Data.png",
    name: "Fragmented Signal Data",
    rarity: 11,
  }),
  incomplete_green: new Relic({
    id: "incomplete_green",
    location: {
      node: "Cantina 8-F",
      energy: 16,
    },
    dropRate: 0.93,
    amount: {
      1: 0,
      2: 0,
      3: 15,
      4: 25,
      5: 25,
      6: 25,
      7: 25,
      8: 25,
      9: 30,
    },
    image:
      "https://wiki.swgoh.help/images/2/26/Gear-Incomplete_Signal_Data.png",
    name: "Incomplete Signal Data",
    rarity: 12,
  }),
  flawed_blue: new Relic({
    id: "flawed_blue",
    location: {
      node: "Cantina 8-G",
      energy: 16,
    },
    dropRate: 0.66,
    amount: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 15,
      6: 25,
      7: 35,
      8: 45,
      9: 55,
    },
    image: "https://wiki.swgoh.help/images/b/b7/Gear-Flawed_Signal_Data.png",
    name: "Flawed Signal Data",
    rarity: 13,
  }),
  carbonite_circuit_board: new Relic({
    id: "carbonite_circuit_board",
    location: {
      node: "Jawa Scavenger",
    },
    amount: {
      1: 40,
      2: 30,
      3: 30,
      4: 30,
      5: 30,
      6: 20,
      7: 20,
      8: 0,
      9: 0,
    },
    image:
      "https://wiki.swgoh.help/images/6/6d/Gear-Carbonite_Circuit_Board.png",
    name: "Carbonite Circuit Board",
    rarity: 1,
  }),
  bronzium_wiring: new Relic({
    id: "bronzium_wiring",
    location: {
      node: "Jawa Scavenger",
    },
    amount: {
      1: 0,
      2: 40,
      3: 40,
      4: 40,
      5: 40,
      6: 30,
      7: 30,
      8: 0,
      9: 0,
    },
    image: "https://wiki.swgoh.help/images/e/e0/Gear-Bronzium_Wiring.png",
    name: "Bronzium Wiring",
    rarity: 2,
  }),
  chromium_transistor: new Relic({
    id: "chromium_transistor",
    location: {
      node: "Jawa Scavenger",
    },
    amount: {
      1: 0,
      2: 0,
      3: 20,
      4: 40,
      5: 30,
      6: 30,
      7: 20,
      8: 20,
      9: 20,
    },
    image: "https://wiki.swgoh.help/images/2/23/Gear-Chromium_Transistor.png",
    name: "Chromium Transistor",
    rarity: 3,
  }),
  aurodium_heatsink: new Relic({
    id: "aurodium_heatsink",
    location: {
      node: "Jawa Scavenger",
    },
    amount: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 20,
      6: 20,
      7: 20,
      8: 20,
      9: 20,
    },
    image: "https://wiki.swgoh.help/images/5/52/Gear-Aurodium_Heatsink.png",
    name: "Aurodium Heatsink",
    rarity: 4,
  }),
  electrium_conductor: new Relic({
    id: "electrium_conductor",
    location: {
      node: "Jawa Scavenger",
    },
    amount: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
      6: 20,
      7: 20,
      8: 20,
      9: 20,
    },
    image: "https://wiki.swgoh.help/images/7/7b/Gear-Electrium_Conductor.png",
    name: "Electrium Conductor",
    rarity: 5,
  }),
  zinbiddle_card: new Relic({
    id: "zinbiddle_card",
    location: {
      node: "Jawa Scavenger",
    },
    amount: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
      6: 0,
      7: 10,
      8: 20,
      9: 20,
    },
    image: "https://wiki.swgoh.help/images/2/2e/Game-Icon-Zinbiddle_Card.png",
    name: "Zinbiddle Card",
    rarity: 6,
  }),
  impulse_detector: new Relic({
    id: "impulse_detector",
    location: {
      node: "Jawa Scavenger",
    },
    amount: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
      6: 0,
      7: 0,
      8: 20,
      9: 20,
    },
    image: "https://wiki.swgoh.help/images/1/1a/Game-Icon-Impulse_Detector.png",
    name: "Impulse Detector",
    rarity: 7,
  }),
  aeromagnifier: new Relic({
    id: "aeromagnifier",
    location: {
      node: "Jawa Scavenger",
    },
    amount: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
      6: 0,
      7: 0,
      8: 20,
      9: 20,
    },
    image: "https://wiki.swgoh.help/images/6/6a/Game-Icon-Aeromagnifier.png",
    name: "Aeromagnifier",
    rarity: 8,
  }),
  gyrda_keypad: new Relic({
    id: "gyrda_keypad",
    location: {
      node: "Jawa Scavenger",
    },
    amount: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
      6: 0,
      7: 0,
      8: 0,
      9: 20,
    },
    image: "https://wiki.swgoh.help/images/6/67/Game-Icon-Gyrda_Keypad.png",
    name: "Gyrda Keypad",
    rarity: 9,
  }),
  droid_brains: new Relic({
    id: "droid_brains",
    location: {
      node: "Jawa Scavenger",
    },
    amount: {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
      6: 0,
      7: 0,
      8: 0,
      9: 20,
    },
    image: "https://wiki.swgoh.help/images/0/0f/Game-Icon-Droid_Brain.png",
    name: "Droid Brains",
    rarity: 10,
  }),
} as RelicConfigType;
